name: Lint

on: pull_request

jobs:
  eslint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install modules
        run: npm install
      - if: ${{ github.event_name == 'push' || github.event.pull_request.head.repo.full_name == github.repository }} 
        name: Run ESLint
        run: npm run lint
